"""Strict adapters for checkpoint curves from the transfer discovery evaluator.

The original evaluator and historical reference identities remain in provenance.
These records belong to a new, explicitly selected comparison attempt; importing
validated references does not pretend they were generated by the new launcher.
"""
from __future__ import annotations

from copy import deepcopy
import hashlib
import json
import math
from pathlib import Path
import statistics

from utils.eval_series import SeriesError, validate_record

PROTOCOL = 'inner-sac-transfer-checkpoint-curves-v1'
PRIOR_ID = 'prior'
COLORS = ('#0072b2', '#d55e00', '#009e73', '#777777', '#b59b71', '#cc79a7')
POINT_COLUMNS = ['step','setting','label','segment','state','return_mean','return_std',
    'return_lower','return_upper','gain_mean','gain_std','gain_lower','gain_upper',
    'fresh_setting','fresh_gain_mean','fresh_gain_std','fresh_gain_lower','fresh_gain_upper',
    'fresh_segment','fresh_comparison_state','return_min',
    'control_seconds','control_std','control_lower','control_upper',
    'late_seconds','late_std','late_lower','late_upper','episodes','interval_not_applicable']
PROGRESS_COLUMNS = ['step','setting','label','state','completed_episodes','seed','decision','error']


def read(path):
    return json.loads(Path(path).read_text())


def digest(path):
    value = hashlib.sha256()
    with Path(path).open('rb') as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b''):
            value.update(block)
    return value.hexdigest()


def require(condition, message):
    if not condition:
        raise SeriesError(message)


def finite(value, label):
    require(type(value) in (int, float) and math.isfinite(value), 'Invalid ' + label)
    return float(value)


def moments(values):
    return statistics.mean(values), statistics.stdev(values) if len(values) > 1 else None


def settings(campaign):
    rows = [dict(setting_id=PRIOR_ID, label='Prior mean (no inner solve)', color='#000000')]
    require(len(campaign['candidates']) <= len(COLORS), 'Add explicit colors before publishing more than six candidates.')
    rows.extend(dict(candidate, color=COLORS[index]) for index,candidate in enumerate(campaign['candidates']))
    require(len({row['setting_id'] for row in rows}) == len(rows), 'Duplicate setting IDs.')
    require(len({row['label'] for row in rows}) == len(rows), 'Duplicate curve labels.')
    return rows


def identity(campaign, setting):
    require(campaign['protocol'] == PROTOCOL, 'Wrong curve campaign protocol.')
    require(campaign['seeds'] == [101,102,103,104,105] and campaign['controller_seed'] == 55
            and campaign['max_steps'] == 500, 'Curve protocol requires the fixed five-seed full episodes.')
    prior = setting['setting_id'] == PRIOR_ID
    return dict(backbone=campaign['source_run'],
        planner=dict(type='prior' if prior else 'sac', backend='validated-transfer-checkpoint-comparison-v1',
            action_rule='tanh_mean', setting_id=setting['setting_id'],
            settings={} if prior else dict(inner_rounds=setting['J'], inner_rollout_horizon=setting['H'],
                arm=setting['arm'], arm_definition=deepcopy(setting['arm_definition']))),
        protocol=dict(mode='episodes', name=PROTOCOL, environment_seeds=list(campaign['seeds']),
            controller_seed=campaign['controller_seed'], max_steps=campaign['max_steps'],
            action_rule='tanh_mean', paired_reference='same-checkpoint prior mean, identical environment seeds',
            timing='controller wall time including initialization and transfer, excluding diagnostics; steady excludes decisions 0..9'),
        science=dict(adapter='transfer-checkpoint-publication-v1',
            comparison_source=deepcopy(campaign['scientific_source']),
            historical_compatibility=deepcopy(campaign.get('historical_compatibility')),
            prior_import='exact checkpoint/source, full episodes, no-inner mean action and frozen-state validation'))


def _episodes(episodes, campaign):
    """Select the explicit evaluation seeds, never relabel legacy seeds."""
    indexed = {row['seed']:row for row in episodes}
    require(len(indexed) == len(episodes), 'Duplicate episode seed.')
    require(set(campaign['seeds']) <= set(indexed), 'Missing requested episode seed.')
    from utils.ambi_benchmark import solver_seed
    result = []
    for seed in campaign['seeds']:
        row = deepcopy(indexed[seed])
        length = row.get('length', row.get('steps'))
        require(length == campaign['max_steps'] == 500, 'Expected a full 500-decision episode.')
        require(row.get('solver_seed',row.get('episode_solver_seed')) ==
                solver_seed(campaign['controller_seed'],'episode',seed), 'Solver seed identity differs.')
        require(row.get('truncated') is True and row.get('terminated') is False
                and not row.get('truncated_by_evaluator',False) and not row.get('smoke',False),
                'Episode completion flags differ from the full Humanoid protocol.')
        row.update(length=length, solver_seed=solver_seed(campaign['controller_seed'],'episode',seed),
                   **{'return':finite(row.get('return',row.get('return_value')),'episode return')})
        result.append(row)
    return result


def _record(campaign, setting, checkpoint, episodes, files, provenance, path, metrics):
    ident = identity(campaign,setting)
    cp = dict(step=checkpoint['step'],sha256=checkpoint['checkpoint_sha256'])
    fingerprint = hashlib.sha256(json.dumps(dict(identity=ident,checkpoint=cp,
        episodes=[{key:row[key] for key in ('seed','solver_seed','return','length')} for row in episodes]),
        sort_keys=True,separators=(',',':')).encode()).hexdigest()
    return validate_record(dict(identity=ident, checkpoint=cp, metrics=metrics, episodes=episodes,
        artifact_files={key:str(Path(value).resolve()) for key,value in files.items()}, provenance=provenance,
        record_id=fingerprint, source_result_path=str(Path(path).resolve()), label=setting['label']))


def normalize_prior(campaign, checkpoint, pin):
    """Validate a historical no-inner bundle, selecting only requested seeds."""
    path = Path(pin['bundle'])/'manifest.json'
    manifest = read(path)
    require(digest(path) == pin['manifest_sha256'], 'Prior manifest changed.')
    cp = manifest['checkpoint']
    require(manifest.get('status') == 'complete' and cp.get('source_run') == campaign['source_run'], 'Prior source/completion differs.')
    require(cp['sha256'] == checkpoint['checkpoint_sha256']
            and cp['metadata']['checkpoint']['step'] == checkpoint['step'], 'Prior checkpoint differs.')
    require(pin.get('checkpoint_step') == checkpoint['step'] and pin.get('checkpoint_sha256') == checkpoint['checkpoint_sha256'],
            'Prior checkpoint pin differs.')
    metadata_path=Path(checkpoint['metadata'])
    require(digest(metadata_path) == checkpoint['metadata_sha256'] and cp['metadata'] == read(metadata_path),
            'Prior embedded metadata differs from the verified checkpoint sidecar.')
    require(manifest.get('code') == checkpoint['prior_manifest_code'], 'Prior implementation identity differs from its pin.')
    runs = [row for row in manifest['runs'] if not pin.get('selector') or row.get('selector') == pin['selector']]
    require(len(runs) == 1, 'Prior pin must select exactly one run.')
    run, = runs
    result, cfg, protocol = run['result'],run['resolved_config'],manifest['protocol']
    require(cfg.get('inner_operator') == 'none' and cfg.get('inner_actor_source') == 'sac'
            and result.get('action_rule',protocol.get('action_rule')) == protocol.get('action_rule') == 'tanh_mean',
            'Reference is not a no-inner mean policy.')
    environment=protocol.get('environment',{})
    require(environment.get('id') == 'DMControl-v0' and environment.get('params',{}).get('task') == 'humanoid-walk'
            and protocol.get('observation') == 'state' and protocol.get('seed_scheme') == 'sha256-v1',
            'Prior environment/observation/seed scheme differs.')
    require(manifest.get('code',{}).get('dirty') is False, 'Prior implementation was not a clean recorded checkout.')
    require(protocol.get('controller_seed') == campaign['controller_seed'] and protocol.get('max_steps') == 500,
            'Prior controller seed/horizon differs.')
    require(result.get('outer_state_unchanged') is True and type(result.get('outer_updates_before')) is int
            and result['outer_updates_before'] == result.get('outer_updates_after'), 'Prior frozen-state check failed.')
    episodes = _episodes(run.get('episodes') or result['episodes'],campaign)
    if result.get('episodes'):
        alternate = _episodes(result['episodes'],campaign)
        require([(row['seed'],row['return'],row['length']) for row in alternate] ==
                [(row['seed'],row['return'],row['length']) for row in episodes], 'Prior episode copies differ.')
    mean,std = moments([row['return'] for row in episodes])
    metrics = {'eval/return_mean':mean,'eval/return_sample_std':std,'eval/episodes':len(episodes),
        'eval/return_min':min(row['return'] for row in episodes),
        'eval/paired_gain_mean':0.,'eval/paired_gain_sample_std':0.,'eval/paired_episodes':len(episodes),
        'eval/frozen_state_unchanged':True,'runtime/late_control_seconds_per_decision':None,
        'runtime/late_control_sample_std':None,'runtime/late_timing_available':False,
        'runtime/control_seconds_per_decision':None,'runtime/control_sample_std':None,
        'work/environment_decisions':sum(row['length'] for row in episodes)}
    files = {'prior-manifest.json':path}
    # Retain verified legacy traces; missing historical timing is never imputed.
    for name in run.get('trace_files',[]):
        trace = (path.parent/name).resolve()
        require(trace.is_relative_to(path.parent.resolve()), 'Prior trace escapes bundle.')
        require(trace.is_file(), 'Prior trace is missing.')
        if 'trace_sha256' in pin:
            require(digest(trace) == pin['trace_sha256'].get(name), 'Prior trace hash differs.')
        files['prior-traces/'+name] = trace
    provenance = dict(import_kind='validated-historical-prior', original_code=manifest.get('code'),
        original_protocol=protocol, original_environment_seeds=result.get('environment_seeds'),
        selected_environment_seeds=campaign['seeds'], original_source=cp.get('source_run'),
        source_manifest_sha256=pin['manifest_sha256'], timing_status='historical late timing unavailable',
        resolved_config=cfg, checkpoint_metadata=cp['metadata'])
    return _record(campaign,settings(campaign)[0],checkpoint,episodes,files,provenance,path,metrics)


def normalize_transfer(campaign, cell, receipt, result, manifest, prior, *, receipt_path):
    """The worker's strict receipt verifier must run before this adapter."""
    cp = campaign['checkpoints'][cell['checkpoint_index']]
    require(prior['checkpoint'] == dict(step=cp['step'],sha256=cp['checkpoint_sha256']), 'Paired prior checkpoint differs.')
    require(result.get('frozen_outer_verified') is True and result.get('complete') is True
            and result.get('smoke') is False, 'Transfer completion/frozen-state proof missing.')
    require(manifest['checkpoint_sha256'] == cp['checkpoint_sha256'] and manifest['checkpoint_step'] == cp['step'],
            'Transfer checkpoint differs.')
    require((manifest['horizon'],manifest['rounds'],manifest['arm']) == (cell['H'],cell['J'],cell['arm']),
            'Transfer setting differs.')
    require(manifest['seeds'] == campaign['seeds'] and manifest['controller_seed'] == campaign['controller_seed']
            and manifest['max_steps'] == 500 and manifest['semantics']['action'] == 'adapted_actor_mean',
            'Transfer episode protocol differs.')
    directory = Path(cell['result_dir'])
    episodes = _episodes(result['episodes'],campaign)
    lookup = {row['seed']:row for row in prior['episodes']}
    files = {'manifest.json':directory/'manifest.json','results.json':directory/'results.json',
             'worker-receipt.json':receipt_path, **{'reference/'+key:value for key,value in prior['artifact_files'].items()}}
    late=[]; full=[]
    for episode in episodes:
        path = directory/f"decisions-seed-{episode['seed']}.jsonl"
        rows = [json.loads(line) for line in path.read_text().splitlines() if line.strip()]
        require(len(rows)==500 and [row['decision'] for row in rows]==list(range(500))
                and all(row['seed']==episode['seed'] for row in rows),'Transfer decision trace coverage differs.')
        controls=[finite(row['control_seconds'],'controller timing') for row in rows]
        require(all(value>=0 for value in controls),'Negative controller time.')
        require(math.isclose(sum(controls),episode['control_seconds'],rel_tol=1e-8,abs_tol=1e-6),'Controller timing sum differs.')
        require(math.isclose(sum(row['reward'] for row in rows),episode['return'],rel_tol=1e-8,abs_tol=1e-6),'Reward sum differs.')
        episode['late_control_seconds_per_decision']=statistics.mean(controls[10:])
        episode['control_seconds_per_decision']=statistics.mean(controls)
        episode['paired_return_delta']=episode['return']-lookup[episode['seed']]['return']
        late.append(episode['late_control_seconds_per_decision'])
        full.append(episode['control_seconds_per_decision'])
        files[path.name]=path
    mean,std=moments([row['return'] for row in episodes]); gain,gain_std=moments([row['paired_return_delta'] for row in episodes])
    cost,cost_std=moments(late)
    full_cost,full_std=moments(full)
    metrics={'eval/return_mean':mean,'eval/return_sample_std':std,'eval/episodes':len(episodes),
        'eval/paired_gain_mean':gain,'eval/paired_gain_sample_std':gain_std,'eval/paired_episodes':len(episodes),
        'eval/return_min':min(row['return'] for row in episodes),
        'eval/frozen_state_unchanged':True,'runtime/control_seconds':sum(row['control_seconds'] for row in episodes),
        'runtime/control_seconds_per_decision':full_cost,'runtime/control_sample_std':full_std,
        'runtime/late_control_seconds_per_decision':cost,'runtime/late_control_sample_std':cost_std,
        'runtime/late_timing_available':True,'work/environment_decisions':sum(row['length'] for row in episodes)}
    setting=next(row for row in settings(campaign) if row['setting_id']==cell['setting_id'])
    provenance=dict(import_kind='validated-transfer-campaign-cell', original_source=manifest['source'],
        original_campaign_sha256=manifest['campaign_sha256'], worker_receipt=deepcopy(receipt),
        prior_record_id=prior['record_id'], prior_source=deepcopy(prior['provenance']),
        resolved_config=manifest['resolved'], timing_decision_range=[10,499])
    return _record(campaign,setting,cp,episodes,files,provenance,directory/'results.json',metrics)


def fresh_setting(campaign, setting):
    """Resolve the exact H/J fresh control, independently of publication order."""
    if setting['setting_id'] == PRIOR_ID:
        return None
    choices = [row for row in campaign['candidates']
               if row['H'] == setting['H'] and row['J'] == setting['J']
               and row.get('role') == 'fresh']
    explicit = setting.get('fresh_setting_id')
    if explicit:
        choices = [row for row in choices if row['setting_id'] == explicit]
    require(len(choices) <= 1, 'Ambiguous matched fresh control.')
    if setting.get('role') in ('transfer','fresh'):
        require(len(choices) == 1, 'Missing matched fresh control for the selected H/J.')
    return choices[0]['setting_id'] if choices else None


def paired_fresh(campaign, record, reference):
    require(record['checkpoint'] == reference['checkpoint'], 'Fresh control checkpoint differs.')
    candidate_planner, fresh_planner = record['identity']['planner'], reference['identity']['planner']
    for name in ('inner_rounds', 'inner_rollout_horizon'):
        require(candidate_planner['settings'][name] == fresh_planner['settings'][name],
                'Fresh control solve budget differs.')
    candidate = _episodes(record['episodes'], campaign)
    lookup = {row['seed']:row for row in _episodes(reference['episodes'], campaign)}
    return moments([row['return'] - lookup[row['seed']]['return'] for row in candidate])


def table_rows(campaign, setting, records, progress, fresh_records=None):
    """Null pending values plus explicit segments avoid bridging missing checkpoints."""
    points,states=[],[]
    segment=0; fresh_segment=0
    matched = fresh_setting(campaign, setting)
    fresh_records = fresh_records or {}
    for checkpoint in sorted(campaign['checkpoints'],key=lambda row:row['step']):
        step=checkpoint['step']; record=records.get(step); status=progress.get(step,{})
        state='complete' if record else status.get('state','pending')
        base=dict(step=step,setting=setting['setting_id'],label=setting['label'],state=state)
        row=dict(base,segment=segment,fresh_segment=fresh_segment,episodes=0,
                 fresh_setting=matched,fresh_comparison_state='not_applicable' if not matched else 'pending')
        for key in POINT_COLUMNS:
            row.setdefault(key,None)
        if record:
            metrics=record['metrics']; row['episodes']=metrics['eval/episodes']
            for prefix,mean_key,std_key in (('return','eval/return_mean','eval/return_sample_std'),
                ('gain','eval/paired_gain_mean','eval/paired_gain_sample_std'),
                ('control','runtime/control_seconds_per_decision','runtime/control_sample_std'),
                ('late','runtime/late_control_seconds_per_decision','runtime/late_control_sample_std')):
                mean,std=metrics.get(mean_key),metrics.get(std_key)
                row[prefix+'_seconds' if prefix in ('late','control') else prefix+'_mean']=mean
                row[prefix+'_std']=std
                row[prefix+'_lower']=None if mean is None or std is None else mean-std
                row[prefix+'_upper']=None if mean is None or std is None else mean+std
            row['return_min'] = metrics['eval/return_min']
            reference = fresh_records.get(step)
            if matched and reference:
                require(reference['identity']['planner']['setting_id'] == matched,
                        'Fresh control setting identity differs.')
                mean, std = paired_fresh(campaign, record, reference)
                row.update(fresh_gain_mean=mean,fresh_gain_std=std,
                    fresh_gain_lower=mean-std,fresh_gain_upper=mean+std,
                    fresh_comparison_state='complete')
        else:
            segment+=1
        if row['fresh_gain_mean'] is None:
            fresh_segment += 1
        points.append(row)
        states.append(dict(base,completed_episodes=row['episodes'] or status.get('completed_episodes',0),
            seed=status.get('seed'),decision=status.get('decision'),error=status.get('error')))
    return points,states
